//it is parent of all pages so it is applied to all pages :)

import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer/Footer";
import Navbar from "@/components/navbar/Navbar";
import { UserProvider } from "@/context/UserContext";
import ReactQueryProvider from '@/provider/react-query'



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Color Memoir | Colorize your History",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProvider>
        <UserProvider>
          <div className="container">
            <Navbar />
            {children}
            <Footer />
          </div>
        </UserProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
